// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iivaspuvtwylkhpgftqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdmFzcHV2dHd5bGtocGdmdHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDU4NTksImV4cCI6MjA2ODY4MTg1OX0.F0yULAOFfBz5I5yLhvCiJg4-jyiqEcQJlVukUhrN2ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});